apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: wordpress
spec:
  storageClassName: ""
  volumeName: mariadb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
